<?xml version="1.0" encoding="utf-8"?><Database Name="x3v5s" Class="DataClassesVpretDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.[USER]" Member="USER">
    <Type Name="USER">
      <Column Name="[USER]" Member="USERNAME" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[RIGHT]" Member="RIGHT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="VINGENIERI.SDELIVERY" Member="SDELIVERY">
    <Type Name="SDELIVERY">
      <Column Name="STOFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SDHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SDHCAT_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LND_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SALFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SIHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="INVORN_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SISNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SISDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BPCORD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCINV_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCPYR_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCGRU_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPAADD_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PJT_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SHIDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SHIHOU_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DLVDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DLVHOU_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DAYLTI_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="HOULTI_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="LNDRTNDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BPDNAM_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPDNAM_1" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPDADDLIG_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDADDLIG_1" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDADDLIG_2" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDPOSCOD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPDCTY_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDSAT_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPDCRY_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BPDCRYNAM_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CNDNAM_0" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="BPINAM_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPINAM_1" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPIADDLIG_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIADDLIG_1" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIADDLIG_2" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIPOSCOD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPICTY_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPISAT_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPICRY_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BPICRYNAM_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIEECNUM_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CNINAM_0" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="REP_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="REP_1" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CUR_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CHGTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CHGRAT_0" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="LAN_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="VACBPR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PTE_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_1" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_2" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_3" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_4" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DEP_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="DRN_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BPTNUM_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MDL_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="INVPER_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DUDCLC_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IME_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SOHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="NTRFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NPRFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NDEFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PRNNPR_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PRNNDE_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="COPNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CFMFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PRFNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BETFCY_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BETCPY_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ORIFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PRHFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PRPTEX1_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="PRPTEX2_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SDHTEX1_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SDHTEX2_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_0" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_1" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_2" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_3" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_4" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_5" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_6" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_7" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_8" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_9" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_7" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_8" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_9" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PRITYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVNOT_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="DLVATI_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_1" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_2" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_3" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_4" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_5" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_6" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_7" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_8" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_7" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_8" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="LINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RTNLINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RTNSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BPCLOC_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LBENUM_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PACNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PACFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="WEU_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="VOU_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NETWEI_0" Type="System.Decimal" DbType="Decimal(13,4) NOT NULL" CanBeNull="false" />
      <Column Name="GROWEI_0" Type="System.Decimal" DbType="Decimal(13,4) NOT NULL" CanBeNull="false" />
      <Column Name="VOL_0" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="EECNAT_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="EECSCH_0" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="EECLOC_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="EECTRN_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="EECICT_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="GEOCOD_0" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="INSCTYFLG_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VTT_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AMTTAX_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="BASTAX_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="LICPLATE_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ETD_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ETA_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TRSFAM_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TRSCOD_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ENTCOD_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CAI_0" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="DATVLYCAI_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EXPNUM_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CREDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UPDUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UPDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Z_TRKNUM_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Z_SECCOM_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ROWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="SDELIVERY_SDELIVERYD" Member="SDELIVERYD" ThisKey="SDHNUM_0" OtherKey="SDHNUM_0" Type="SDELIVERYD" />
      <Association Name="SDELIVERY_SORDER" Member="SORDER" ThisKey="SOHNUM_0" OtherKey="SOHNUM_0" Type="SORDER" />
    </Type>
  </Table>
  <Table Name="VINGENIERI.SDELIVERYD" Member="SDELIVERYD">
    <Type Name="SDELIVERYD">
      <Column Name="SDHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SDDLIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOHCAT_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SOHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SOPLIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOQSEQ_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BPCORD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPAADD_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="ITMREF_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ITMDES1_0" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ITMDES_0" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VACITM_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="VACITM_1" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="VACITM_2" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="STOFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="USEPLC_0" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SHIDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="REP1_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="REP2_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="REPRAT1_0" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="REPRAT2_0" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="REPCOE_0" Type="System.Decimal" DbType="Decimal(6,3) NOT NULL" CanBeNull="false" />
      <Column Name="GROPRI_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="PRIREN_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="NETPRI_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="NETPRINOT_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="NETPRIATI_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="PFM_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="CPRPRI_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL1_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL2_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL3_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL4_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL5_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL6_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL7_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL8_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGVAL9_0" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN1_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN2_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN3_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN4_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN5_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN6_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN7_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN8_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGREN9_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VAT_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="VAT_1" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="VAT_2" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CLCAMT1_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="CLCAMT2_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="QTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="QTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="RTNQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="RTNQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="WRTQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="WRTQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="OALQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="SAU_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="STU_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="SAUSTUCOE_0" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="TSICOD_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSICOD_1" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSICOD_2" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSICOD_3" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSICOD_4" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CCE1_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE2_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE3_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE4_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE5_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE6_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE7_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE8_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE9_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PCK_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PCKCAP_0" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="LINTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FOCFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ORILIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STOMGTCOD_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LOT_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="STA_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="LOC_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WEU_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="UNTWEI_0" Type="System.Decimal" DbType="Decimal(13,4) NOT NULL" CanBeNull="false" />
      <Column Name="SDDTEX_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="PRPTEX_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="GEOCOD_0" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="INSCTYFLG_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VTS_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VTC_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TAXGEOFLG_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TAXFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TAXREGFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RATTAXLIN_0" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="BASTAXLIN_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="NDEPRNBOM_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVPRNBOM_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RCPFLG_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RCPQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="MFGNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MFGLIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BOMSEQ_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="EXPNUM_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CREDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UPDUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UPDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ROWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="SDELIVERY_SDELIVERYD" Member="SDELIVERY" ThisKey="SDHNUM_0" OtherKey="SDHNUM_0" Type="SDELIVERY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="VINGENIERI.SORDER" Member="SORDER">
    <Type Name="SORDER">
      <Column Name="SOHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SOHTYP_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="SOHCAT_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SALFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="BPCORD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCINV_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCPYR_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCGRU_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPAADD_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CUSORDREF_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PJT_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ORDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VLYDATCON_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SHIDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEMDLVDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LNDRTNDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DAYLTI_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BPCNAM_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPCNAM_1" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPCADDLIG_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPCADDLIG_1" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPCADDLIG_2" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPCPOSCOD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPCCTY_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPCSAT_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPCCRY_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BPCCRYNAM_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CNTNAM_0" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="BPINAM_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPINAM_1" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPIADDLIG_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIADDLIG_1" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIADDLIG_2" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIPOSCOD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPICTY_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPISAT_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPICRY_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BPICRYNAM_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPIEECNUM_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CNINAM_0" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="BPDNAM_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPDNAM_1" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPDADDLIG_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDADDLIG_1" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDADDLIG_2" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDPOSCOD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPDCTY_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="BPDSAT_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="BPDCRY_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BPDCRYNAM_0" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CNDNAM_0" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="REP_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="REP_1" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CUR_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CHGTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CHGRAT_0" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_1" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_2" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_3" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_4" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_5" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_6" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_7" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CCE_8" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="LAN_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="VACBPR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PTE_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_1" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_2" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_3" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TSCCOD_4" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DEP_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BPTNUM_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MDL_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="STOFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DRN_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVPIO_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ORDCLE_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ODL_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DME_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IME_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="OCNFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="OCNPRN_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="COPNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SOHTEX1_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SOHTEX2_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SQHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BETFCY_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BETCPY_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ORIFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PRFNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="LASDLVNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="LASDLVDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LASINVNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="LASINVDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_0" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_1" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_2" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_3" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_4" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_5" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_6" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_7" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_8" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTAAMT_9" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_7" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_8" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTA_9" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PRITYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ORDNOT_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="ORDATI_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="ORDINVNOT_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="ORDINVATI_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="DLRNOT_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="DLRATI_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="PFMTOT_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_1" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_2" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_3" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_4" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_5" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_6" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_7" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DISCRGTYP_8" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_7" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVDTALIN_8" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ALLTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UNL_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CLELINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ALLLINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVLINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVLINNBR_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ORDSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ALLSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CDTSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="REVNUM_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SHIADECOD_0" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="GEOCOD_0" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="INSCTYFLG_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VTT_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AMTTAX_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="BASTAX_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="CCLREN_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CCLDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SRENUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CMGNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="OPGNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="OPGTYP_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="EXPNUM_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SINUM_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CREUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CREDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UPDUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UPDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Z_FLGPRE_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Z_SECCOM_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ROWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="SDELIVERY_SORDER" Member="SDELIVERY" ThisKey="SOHNUM_0" OtherKey="SOHNUM_0" Type="SDELIVERY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="VINGENIERI.SORDERQ" Member="SORDERQ">
    <Type Name="SORDERQ">
      <Column Name="SOHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SOPLIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOQSEQ_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOHCAT_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SALFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="BPCORD_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BPAADD_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="ITMREF_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="STOFCY_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="USEPLC_0" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CAD_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="YEA_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MON_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVDAY_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="WEE_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ORDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEMDLVDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEMDLVHOU_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DEMDLVREF_0" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IMPNUMLIG_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SHIDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SHIHOU_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="EXTDLVDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SOQSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DEMSTA_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DEMNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="STOMGTCOD_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LOT_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="STA_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="LOC_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ALLTYP_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ORIQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="QTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="SHTQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="ALLQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="ODLQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="DLVQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="INVQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="TDLQTY_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="QTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="SHTQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="ALLQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="ODLQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="DLVQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="INVQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="TDLQTYSTU_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="DRN_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVPIO_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DLVPIOCMP_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BPTNUM_0" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MDL_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="DAYLTI_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PCK_0" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PCKCAP_0" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="SOQTEX_0" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SDHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SDDLIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FMI_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FMINUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="FMILIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FMISEQ_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="POHNUM_0" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="POPLIN_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="POQSEQ_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PERSTRDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PERENDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PERNBRDAY_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="GEOCOD_0" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="INSCTYFLG_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VTS_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VTC_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TAXGEOFLG_0" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TAXFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TAXREGFLG_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RATTAXLIN_0" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="BASTAXLIN_0" Type="System.Decimal" DbType="Decimal(27,13) NOT NULL" CanBeNull="false" />
      <Column Name="OCNPRNBOM_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NDEPRNBOM_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INVPRNBOM_0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CCLREN_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CCLDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PITFLG_0" Type="System.Decimal" DbType="Decimal(28,13) NOT NULL" CanBeNull="false" />
      <Column Name="EXPNUM_0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CREDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UPDUSR_0" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="UPDDAT_0" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ROWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>